disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace

opt_in_rules: # some rules are only opt-in

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting.
- Pods

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)

force_cast: warning # implicitly

force_try:

severity: warning # explicitly

line_length: 110

type_body_length:
- 500 # warning
- 600 # error

file_length:

warning: 100

error: 200

type_name:

min_length: 4 # only warning

max_length: # warning and error

warning: 40

error: 50

excluded: iPhone # excluded via string

identifier_name:

min_length: # only min_length

error: 4 # only error

excluded: # excluded via string array

reporter: "xcode"
